---
- name: install package php and mariadb
  hosts: dev,test,prod
  tasks:
    - name: install
      yum:
        name:
          - php
          - mariadb
          - "@RPM Development Tools"
        state: present
    - name: update all packages
      yum:
        name: '*'
        state: latest